/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.johnrengelman.shadow") version "7.1.0"
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_5
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenCentral()
}

dependencies {
    implementation("com.maxmind.geoip:geoip-api:1.2.15")
    implementation("org.aspectj:aspectjrt:1.6.12")
    implementation("org.swinglabs.swingx:swingx-core:1.6.5-1")
    implementation("org.eclipse.swt:org.eclipse.swt.gtk.linux.x86_64:4.3")
    implementation("jakarta.management.j2ee:management-spec:1.1.4")

    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

application {
    // Define the main class for the application.
    mainClass.set("org.jmule.main.Main")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
